"""initial schema

Revision ID: 9c500f6cc24d
Revises: 
Create Date: 2026-07-04 16:52:40.585125+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9c500f6cc24d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('username', sa.Text(), nullable=False),
    sa.Column('email', sa.Text(), nullable=True),
    sa.Column('hashed_password', sa.Text(), nullable=False),
    sa.Column('disabled', sa.Boolean(), nullable=False),
    sa.Column('auth_provider', sa.Text(), nullable=True),
    sa.Column('provider_user_id', sa.Text(), nullable=True),
    sa.Column('google_id', sa.Text(), nullable=True),
    sa.Column('nango_connection_id', sa.Text(), nullable=True),
    sa.Column('gmail_sender_email', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('username')
    )
    op.create_index('ix_users_auth_provider_user_id', 'users', ['auth_provider', 'provider_user_id'], unique=False)
    op.create_index('ix_users_email', 'users', ['email'], unique=False)
    op.create_index('ix_users_google_id', 'users', ['google_id'], unique=True, postgresql_where=sa.text('google_id IS NOT NULL'))
    op.create_table('bots',
    sa.Column('bot_id', sa.Text(), nullable=False),
    sa.Column('owner_id', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('business_type', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('total_clients', sa.Integer(), nullable=False),
    sa.Column('total_conversations', sa.Integer(), nullable=False),
    sa.Column('total_messages', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.username'], ),
    sa.PrimaryKeyConstraint('bot_id')
    )
    op.create_index('ix_bots_created_at', 'bots', ['created_at'], unique=False)
    op.create_index('ix_bots_owner_id', 'bots', ['owner_id'], unique=False)
    op.create_index('ix_bots_status', 'bots', ['status'], unique=False)
    op.create_table('channels',
    sa.Column('channel_id', sa.Text(), nullable=False),
    sa.Column('bot_id', sa.Text(), nullable=False),
    sa.Column('channel_type', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('whatsapp_config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('telegram_config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('web_config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('pwa_config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('webhook_url', sa.Text(), nullable=True),
    sa.Column('total_messages_received', sa.Integer(), nullable=False),
    sa.Column('total_messages_sent', sa.Integer(), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_activity_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("channel_type != 'pwa' OR pwa_config IS NOT NULL", name='ck_channels_pwa_config_present'),
    sa.CheckConstraint("channel_type != 'telegram' OR telegram_config IS NOT NULL", name='ck_channels_telegram_config_present'),
    sa.CheckConstraint("channel_type != 'web' OR web_config IS NOT NULL", name='ck_channels_web_config_present'),
    sa.CheckConstraint("channel_type != 'whatsapp' OR whatsapp_config IS NOT NULL", name='ck_channels_whatsapp_config_present'),
    sa.ForeignKeyConstraint(['bot_id'], ['bots.bot_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('channel_id')
    )
    op.create_index('ix_channels_bot_id', 'channels', ['bot_id'], unique=False)
    op.create_index('ix_channels_bot_id_channel_type', 'channels', ['bot_id', 'channel_type'], unique=False)
    op.create_index('ix_channels_status', 'channels', ['status'], unique=False)
    op.create_index('ix_channels_twilio_phone_number', 'channels', [sa.literal_column("(whatsapp_config -> 'twilio_config' ->> 'phone_number')")], unique=False)
    op.create_table('clients',
    sa.Column('client_id', sa.Text(), nullable=False),
    sa.Column('bot_id', sa.Text(), nullable=False),
    sa.Column('external_id', sa.Text(), nullable=False),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('email', sa.Text(), nullable=True),
    sa.Column('phone', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('score', sa.Numeric(), nullable=False),
    sa.Column('total_conversations', sa.Integer(), nullable=False),
    sa.Column('total_messages', sa.Integer(), nullable=False),
    sa.Column('total_tokens_used', sa.Integer(), nullable=False),
    sa.Column('first_contact_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_contact_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['bot_id'], ['bots.bot_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('client_id')
    )
    op.create_index('ix_clients_bot_id_external_id', 'clients', ['bot_id', 'external_id'], unique=True)
    op.create_index('ix_clients_bot_id_status', 'clients', ['bot_id', 'status'], unique=False)
    op.create_index('ix_clients_last_contact_at', 'clients', ['last_contact_at'], unique=False)
    op.create_index('ix_clients_score', 'clients', ['score'], unique=False)
    op.create_table('conversations',
    sa.Column('conversation_id', sa.Text(), nullable=False),
    sa.Column('bot_id', sa.Text(), nullable=True),
    sa.Column('client_id', sa.Text(), nullable=True),
    sa.Column('user_id', sa.Text(), nullable=False),
    sa.Column('channel', sa.Text(), nullable=True),
    sa.Column('source', sa.Text(), nullable=True),
    sa.Column('channel_id', sa.Text(), nullable=True),
    sa.Column('total_tokens_used', sa.Integer(), nullable=False),
    sa.Column('total_cost_usd', sa.Numeric(), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['bot_id'], ['bots.bot_id'], ),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.channel_id'], ),
    sa.ForeignKeyConstraint(['client_id'], ['clients.client_id'], ),
    sa.PrimaryKeyConstraint('conversation_id')
    )
    op.create_index('ix_conversations_bot_id', 'conversations', ['bot_id'], unique=False)
    op.create_index('ix_conversations_client_id', 'conversations', ['client_id'], unique=False)
    op.create_index('ix_conversations_created_at', 'conversations', ['created_at'], unique=False)
    op.create_index('ix_conversations_source', 'conversations', ['source'], unique=False)
    op.create_index('ix_conversations_user_id', 'conversations', ['user_id'], unique=False)
    op.create_table('push_subscriptions',
    sa.Column('subscription_id', sa.Text(), nullable=False),
    sa.Column('bot_id', sa.Text(), nullable=False),
    sa.Column('channel_id', sa.Text(), nullable=True),
    sa.Column('client_id', sa.Text(), nullable=True),
    sa.Column('endpoint', sa.Text(), nullable=False),
    sa.Column('p256dh', sa.Text(), nullable=False),
    sa.Column('auth', sa.Text(), nullable=False),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expiration_time', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['bot_id'], ['bots.bot_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.channel_id'], ),
    sa.ForeignKeyConstraint(['client_id'], ['clients.client_id'], ),
    sa.PrimaryKeyConstraint('subscription_id'),
    sa.UniqueConstraint('endpoint')
    )
    op.create_index('ix_push_subscriptions_bot_id', 'push_subscriptions', ['bot_id'], unique=False)
    op.create_index('ix_push_subscriptions_bot_id_channel_id', 'push_subscriptions', ['bot_id', 'channel_id'], unique=False)
    op.create_index('ix_push_subscriptions_bot_id_is_active', 'push_subscriptions', ['bot_id', 'is_active'], unique=False)
    op.create_index('ix_push_subscriptions_client_id', 'push_subscriptions', ['client_id'], unique=False, postgresql_where=sa.text('client_id IS NOT NULL'))
    op.create_table('messages',
    sa.Column('message_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('conversation_id', sa.Text(), nullable=False),
    sa.Column('role', sa.Text(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.CheckConstraint("role IN ('user', 'assistant')", name='ck_messages_role'),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.conversation_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('message_id')
    )
    op.create_index('ix_messages_conversation_id_timestamp', 'messages', ['conversation_id', 'timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_messages_conversation_id_timestamp', table_name='messages')
    op.drop_table('messages')
    op.drop_index('ix_push_subscriptions_client_id', table_name='push_subscriptions', postgresql_where=sa.text('client_id IS NOT NULL'))
    op.drop_index('ix_push_subscriptions_bot_id_is_active', table_name='push_subscriptions')
    op.drop_index('ix_push_subscriptions_bot_id_channel_id', table_name='push_subscriptions')
    op.drop_index('ix_push_subscriptions_bot_id', table_name='push_subscriptions')
    op.drop_table('push_subscriptions')
    op.drop_index('ix_conversations_user_id', table_name='conversations')
    op.drop_index('ix_conversations_source', table_name='conversations')
    op.drop_index('ix_conversations_created_at', table_name='conversations')
    op.drop_index('ix_conversations_client_id', table_name='conversations')
    op.drop_index('ix_conversations_bot_id', table_name='conversations')
    op.drop_table('conversations')
    op.drop_index('ix_clients_score', table_name='clients')
    op.drop_index('ix_clients_last_contact_at', table_name='clients')
    op.drop_index('ix_clients_bot_id_status', table_name='clients')
    op.drop_index('ix_clients_bot_id_external_id', table_name='clients')
    op.drop_table('clients')
    op.drop_index('ix_channels_twilio_phone_number', table_name='channels')
    op.drop_index('ix_channels_status', table_name='channels')
    op.drop_index('ix_channels_bot_id_channel_type', table_name='channels')
    op.drop_index('ix_channels_bot_id', table_name='channels')
    op.drop_table('channels')
    op.drop_index('ix_bots_status', table_name='bots')
    op.drop_index('ix_bots_owner_id', table_name='bots')
    op.drop_index('ix_bots_created_at', table_name='bots')
    op.drop_table('bots')
    op.drop_index('ix_users_google_id', table_name='users', postgresql_where=sa.text('google_id IS NOT NULL'))
    op.drop_index('ix_users_email', table_name='users')
    op.drop_index('ix_users_auth_provider_user_id', table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
