"""add tenants, roles and module grants

Revision ID: 8914954753b7
Revises: 6ad0e3a3fbb5
Create Date: 2026-07-06 02:32:06.088983+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8914954753b7'
down_revision: Union[str, None] = '6ad0e3a3fbb5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('modules',
    sa.Column('module_key', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('module_key')
    )
    op.create_table('tenants',
    sa.Column('tenant_id', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('domain', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), server_default='active', nullable=False),
    sa.Column('branding', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('active', 'suspended', 'trial')", name='ck_tenants_status'),
    sa.PrimaryKeyConstraint('tenant_id')
    )
    op.create_index('ix_tenants_domain', 'tenants', ['domain'], unique=True, postgresql_where=sa.text('domain IS NOT NULL'))
    op.create_index('ix_tenants_status', 'tenants', ['status'], unique=False)
    op.create_table('bot_modules',
    sa.Column('bot_id', sa.Text(), nullable=False),
    sa.Column('module_key', sa.Text(), nullable=False),
    sa.Column('granted', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('enabled', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('granted_by', sa.Text(), nullable=True),
    sa.Column('granted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('NOT enabled OR granted', name='ck_bot_modules_enabled_requires_granted'),
    sa.ForeignKeyConstraint(['bot_id'], ['bots.bot_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['granted_by'], ['users.username'], ),
    sa.ForeignKeyConstraint(['module_key'], ['modules.module_key'], ),
    sa.PrimaryKeyConstraint('bot_id', 'module_key')
    )
    op.create_index('ix_bot_modules_module_key', 'bot_modules', ['module_key'], unique=False)
    op.add_column('bots', sa.Column('tenant_id', sa.Text(), nullable=True))
    op.create_index('ix_bots_tenant_id', 'bots', ['tenant_id'], unique=False)
    op.create_foreign_key('fk_bots_tenant_id', 'bots', 'tenants', ['tenant_id'], ['tenant_id'])
    op.add_column('channels', sa.Column('tenant_id', sa.Text(), nullable=True))
    op.create_index('ix_channels_tenant_id', 'channels', ['tenant_id'], unique=False)
    op.create_foreign_key('fk_channels_tenant_id', 'channels', 'tenants', ['tenant_id'], ['tenant_id'])
    op.add_column('clients', sa.Column('tenant_id', sa.Text(), nullable=True))
    op.create_index('ix_clients_tenant_id', 'clients', ['tenant_id'], unique=False)
    op.create_foreign_key('fk_clients_tenant_id', 'clients', 'tenants', ['tenant_id'], ['tenant_id'])
    op.add_column('conversations', sa.Column('tenant_id', sa.Text(), nullable=True))
    op.create_index('ix_conversations_tenant_id', 'conversations', ['tenant_id'], unique=False)
    op.create_foreign_key('fk_conversations_tenant_id', 'conversations', 'tenants', ['tenant_id'], ['tenant_id'])
    op.add_column('push_subscriptions', sa.Column('tenant_id', sa.Text(), nullable=True))
    op.create_index('ix_push_subscriptions_tenant_id', 'push_subscriptions', ['tenant_id'], unique=False)
    op.create_foreign_key('fk_push_subscriptions_tenant_id', 'push_subscriptions', 'tenants', ['tenant_id'], ['tenant_id'])
    op.add_column('users', sa.Column('tenant_id', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('role', sa.Text(), server_default='admin', nullable=False))
    op.create_index('ix_users_tenant_id', 'users', ['tenant_id'], unique=False)
    op.create_foreign_key('fk_users_tenant_id', 'users', 'tenants', ['tenant_id'], ['tenant_id'])

    # Semilla del catálogo de módulos (entitlement layer — ver ADR de estrategia
    # multi-tenant). La modularización real del código queda para más adelante.
    op.execute(
        """
        INSERT INTO modules (module_key, name, description) VALUES
        ('rag', 'Base de conocimiento (RAG)', 'Respuestas basadas en documentos indexados del bot'),
        ('lead_funnel', 'Embudo de conversión', 'Flujo conversacional progresivo de captura de datos (FlowConfig)'),
        ('appointments', 'Turnos', 'Capacidad de agendar turnos/citas')
        """
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_users_tenant_id', 'users', type_='foreignkey')
    op.drop_index('ix_users_tenant_id', table_name='users')
    op.drop_column('users', 'role')
    op.drop_column('users', 'tenant_id')
    op.drop_constraint('fk_push_subscriptions_tenant_id', 'push_subscriptions', type_='foreignkey')
    op.drop_index('ix_push_subscriptions_tenant_id', table_name='push_subscriptions')
    op.drop_column('push_subscriptions', 'tenant_id')
    op.drop_constraint('fk_conversations_tenant_id', 'conversations', type_='foreignkey')
    op.drop_index('ix_conversations_tenant_id', table_name='conversations')
    op.drop_column('conversations', 'tenant_id')
    op.drop_constraint('fk_clients_tenant_id', 'clients', type_='foreignkey')
    op.drop_index('ix_clients_tenant_id', table_name='clients')
    op.drop_column('clients', 'tenant_id')
    op.drop_constraint('fk_channels_tenant_id', 'channels', type_='foreignkey')
    op.drop_index('ix_channels_tenant_id', table_name='channels')
    op.drop_column('channels', 'tenant_id')
    op.drop_constraint('fk_bots_tenant_id', 'bots', type_='foreignkey')
    op.drop_index('ix_bots_tenant_id', table_name='bots')
    op.drop_column('bots', 'tenant_id')
    op.drop_index('ix_bot_modules_module_key', table_name='bot_modules')
    op.drop_table('bot_modules')
    op.drop_index('ix_tenants_status', table_name='tenants')
    op.drop_index('ix_tenants_domain', table_name='tenants', postgresql_where=sa.text('domain IS NOT NULL'))
    op.drop_table('tenants')
    op.drop_table('modules')
    # ### end Alembic commands ###
