"""add prospects table

Revision ID: e3c536fd3fd7
Revises: c4d8e1f6a209
Create Date: 2026-07-12 02:56:38.097026+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e3c536fd3fd7'
down_revision: Union[str, None] = 'c4d8e1f6a209'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prospects',
    sa.Column('prospect_id', sa.Text(), nullable=False),
    sa.Column('tenant_id', sa.Text(), nullable=False),
    sa.Column('estado', sa.Text(), nullable=False),
    sa.Column('nombre', sa.Text(), nullable=False),
    sa.Column('fecha_interaccion', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('canal', sa.Text(), nullable=True),
    sa.Column('whatsapp', sa.Text(), nullable=True),
    sa.Column('email', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.tenant_id'], ),
    sa.PrimaryKeyConstraint('prospect_id')
    )
    op.create_index('ix_prospects_fecha_interaccion', 'prospects', ['fecha_interaccion'], unique=False)
    op.create_index('ix_prospects_tenant_id', 'prospects', ['tenant_id'], unique=False)
    # ### end Alembic commands ###
    # Nota: autogenerate también detectó un cambio cosmético (normalización de
    # expresión) en el índice ix_channels_twilio_phone_number, preexistente y
    # sin relación con esta migración — se omite a propósito.


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_prospects_tenant_id', table_name='prospects')
    op.drop_index('ix_prospects_fecha_interaccion', table_name='prospects')
    op.drop_table('prospects')
    # ### end Alembic commands ###
