"""add nombre apellido avatar_url to users

Revision ID: 35eed6808a87
Revises: e3c536fd3fd7
Create Date: 2026-07-12 03:24:57.831371+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '35eed6808a87'
down_revision: Union[str, None] = 'e3c536fd3fd7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('nombre', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('apellido', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('avatar_url', sa.Text(), nullable=True))
    # ### end Alembic commands ###
    # Nota: autogenerate también detectó un cambio cosmético (normalización de
    # expresión) en el índice ix_channels_twilio_phone_number, preexistente y
    # sin relación con esta migración — se omite a propósito.


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'avatar_url')
    op.drop_column('users', 'apellido')
    op.drop_column('users', 'nombre')
    # ### end Alembic commands ###
