"""enforce tenant_id not null and role consistency

Revision ID: 756beb610685
Revises: 8914954753b7
Create Date: 2026-07-06 02:59:50.911161+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '756beb610685'
down_revision: Union[str, None] = '8914954753b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('bots', 'tenant_id',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('channels', 'tenant_id',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('clients', 'tenant_id',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('push_subscriptions', 'tenant_id',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###

    # No detectado por autogenerate (Alembic no compara CheckConstraints de
    # forma confiable) — agrega la consistencia role/tenant_id ahora que el
    # backfill (Fase 3) ya corrió y todos los usuarios cumplen la regla.
    op.create_check_constraint(
        'ck_users_role_tenant_consistency',
        'users',
        "(role = 'super_admin' AND tenant_id IS NULL) OR "
        "(role IN ('admin', 'operativo') AND tenant_id IS NOT NULL)",
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ck_users_role_tenant_consistency', 'users', type_='check')
    op.alter_column('push_subscriptions', 'tenant_id',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('clients', 'tenant_id',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('channels', 'tenant_id',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('bots', 'tenant_id',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###
